/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    // Documentation generator.
    // https://github.com/Kotlin/dokka
    id("org.jetbrains.dokka") version "1.9.20"

    // https://central.sonatype.org/publish/publish-gradle/
    // https://docs.gradle.org/current/userguide/publishing_maven.html
    `maven-publish`
    signing
}

group = "es.ucm.fdi.demiourgoi"
// https://central.sonatype.org/publish/publish-guide/ only versions with "-SNAPSHOT" suffix can be republished
version = "0.5.0-SNAPSHOT"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin JUnit 5 integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit5")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(20)
    }
    withSourcesJar()
    withJavadocJar()
}

// https://github.com/Kotlin/dokka/issues/42
val javadocJar = tasks.named<Jar>("javadocJar") {
    from(tasks.named("dokkaJavadoc"))
}

base {
    archivesName = rootProject.name
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:complete_example
// https://central.sonatype.org/publish/publish-gradle/#metadata-definition-and-upload
// https://central.sonatype.org/publish/publish-guide/#accessing-repositories
// https://stackoverflow.com/questions/74817917/error-publishing-to-sonatype-because-repositoryurl-is-null
val ossrhRepositoryUrl = if (version.toString().endsWith("SNAPSHOT")) {
    "https://s01.oss.sonatype.org/content/repositories/snapshots/"
} else {
    "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
}
// https://docs.gradle.org/current/userguide/build_environment.html#sec:project_properties
// Maven central credentials should be defined as env vars ORG_GRADLE_PROJECT_ossrhUsername and ORG_GRADLE_PROJECT_ossrhPassword
// See https://central.sonatype.org/publish/generate-token/ for generating credendials
publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            artifactId = "sscheck-core"
            from(components["java"])
            versionMapping {
                usage("java-api") {
                    fromResolutionOf("runtimeClasspath")
                }
                usage("java-runtime") {
                    fromResolutionResult()
                }
            }
            pom {
                name = "Sscheck core"
                description = "Distributed computing engine independent code for sscheck"
                url = "https://github.com/demiourgoi"
                licenses {
                    license {
                        name = "The Apache License, Version 2.0"
                        url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                    }
                }
                developers {
                    developer {
                        id = "juanrh"
                        name = "Juan Rodriguez Hortala"
                        url = "https://juanrh.github.io"
                    }
                }
            }
        }
    }
    repositories {
        maven(ossrhRepositoryUrl) {
            name = "ossrh"
            credentials(PasswordCredentials::class)
        }
    }
}